### ISSUE TITLE
Problem with tinydb version

### ISSUE THREAD

**Issue by davidkleiven** [PhasesResearchLab/ESPEI#126]
We recently tried ESPEI out for one of our projects. However, after installing it we got the following error

```
espei --input espei-input.yaml 
Single phase datasets are present, but there are no specified `excluded_model_contributions` keys present. 'idmix' exclusion will be added automatically for backwards compatibility, but this will go away in ESPEI v0.8. If you want ideal mixing contributions to be excluded, see the documentation for building datasets: http://espei.org/en/latest/input_data.html
Traceback (most recent call last):
  File "/home/alexty/miniconda3/envs/maibat/bin/espei", line 10, in <module>
    sys.exit(main())
  File "/home/alexty/miniconda3/envs/maibat/lib/python3.7/site-packages/espei/espei_script.py", line 311, in main
    run_espei(input_settings)
  File "/home/alexty/miniconda3/envs/maibat/lib/python3.7/site-packages/espei/espei_script.py", line 167, in run_espei
    add_ideal_exclusions(datasets)
  File "/home/alexty/miniconda3/envs/maibat/lib/python3.7/site-packages/espei/datasets.py", line 313, in add_ideal_exclusions
    datasets.write_back(all_single_phase)
  File "/home/alexty/miniconda3/envs/maibat/lib/python3.7/site-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'write_back'
```

if we downgraded *tinydb* to version 3.9 it worked nicely. Has ESPEI been tested with the newest version of *tinydb*?

**Comment by bocklund** [comment]
Thank you for reporting this! It looks like tinydb v4 removed `write_back`. I'm working on a fix now!
