### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by duxiaoxian** [PhasesResearchLab/ESPEI#132]
Dear Administrator,
An 'AttributeError' occurred when I run 'espei --input espei-in-2.yaml' using the latest development version of ESPEI. Would you mind help me to check my dataset? Thanks.
[errorprint-log.txt](https://github.com/PhasesResearchLab/ESPEI/files/5486226/errorprint-log.txt)
[verbosity-log.txt](https://github.com/PhasesResearchLab/ESPEI/files/5486228/verbosity-log.txt)
[CO-CU-20201104.zip](https://github.com/PhasesResearchLab/ESPEI/files/5486229/CO-CU-20201104.zip)

f:\users\zhang\pycalphad\pycalphad\codegen\callables.py:97: UserWarning: State variables in `build_callables` are not {N, P, T}, but {T, P}. This can lead to incorrectly calculated values if the state variables used to call the generated functions do not match the state variables used to create them. State variables can be added with the `additional_statevars` argument.
  "`additional_statevars` argument.".format(state_variables))
Traceback (most recent call last):
  File "F:\Users\zhang\Anaconda32020\envs\espei2020test\Scripts\espei-script.py", line 33, in <module>
    sys.exit(load_entry_point('espei', 'console_scripts', 'espei')())
  File "f:\users\zhang\espei\espei\espei_script.py", line 311, in main
    run_espei(input_settings)
  File "f:\users\zhang\espei\espei\espei_script.py", line 260, in run_espei
    approximate_equilibrium=approximate_equilibrium,
  File "f:\users\zhang\espei\espei\optimizers\opt_base.py", line 36, in fit
    node = self._fit(symbols, datasets, *args, **kwargs)
  File "f:\users\zhang\espei\espei\optimizers\opt_mcmc.py", line 238, in _fit
    self.predict(initial_guess, **ctx)
  File "f:\users\zhang\espei\espei\optimizers\opt_mcmc.py", line 289, in predict
    multi_phase_error = calculate_zpf_error(parameters=np.array(params), **zpf_kwargs)
  File "f:\users\zhang\espei\espei\error_functions\zpf_error.py", line 315, in calculate_zpf_error
    target_hyperplane = estimate_hyperplane(phase_region, parameters, approximate_equilibrium=approximate_equilibrium)
  File "f:\users\zhang\espei\espei\error_functions\zpf_error.py", line 186, in estimate_hyperplane
    grid = calculate_(dbf, species, phases, str_statevar_dict, models, phase_records, pdens=500, fake_points=True)
  File "f:\users\zhang\espei\espei\shadow_functions.py", line 55, in calculate_
    largest_energy=float(1e10), fake_points=fp)
  File "f:\users\zhang\pycalphad\pycalphad\core\calculate.py", line 190, in _compute_phase_values
    param_symbols, parameter_array = extract_parameters(parameters)
  File "f:\users\zhang\pycalphad\pycalphad\core\utils.py", line 361, in extract_parameters
    parameter_array_lengths = set(np.atleast_1d(val).size for val in parameters.values())
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by duxiaoxian** [comment]
My pycalphad also used the latest development version.

**Comment by duxiaoxian** [comment]
At the same time, I use the latest development version to run the successful case that I ran before using espei = 0.7.2, pycalphad = 0.8 also reported an error called KeyError: 'BLANK'. So maybe there is a problem with the latest version.

**Comment by duxiaoxian** [comment]
[AG-CU-20201109-test.zip](https://github.com/PhasesResearchLab/ESPEI/files/5507911/AG-CU-20201109-test.zip)

**Comment by bocklund** [comment]
This should be fixed #133
