### ISSUE TITLE
Error releasing un-acquired lock in dask

### ISSUE THREAD

**Issue by olivia-higgins** [PhasesResearchLab/ESPEI#22]
Was distributed (1.18.0) when this error occurred. Changed to distributed (1.16.3).

```Traceback (most recent call last):
  File "/Applications/anaconda/envs/my_pycalphad/bin/espei", line 11, in <module>
    sys.exit(main())
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/espei/run_espei.py", line 135, in main
    mcmc_steps=args.mcmc_steps, save_interval=args.save_interval)
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/espei/paramselect.py", line 754, in fit
    for i, result in enumerate(sampler.sample(walkers, iterations=mcmc_steps)):
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/emcee/ensemble.py", line 259, in sample
    lnprob[S0])
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/emcee/ensemble.py", line 332, in _propose_stretch
    newlnprob, blob = self._get_lnprob(q)
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/espei/utils.py", line 39, in map
    result = [x.result() for x in result]
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/espei/utils.py", line 39, in <listcomp>
    result = [x.result() for x in result]
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/distributed/client.py", line 155, in result
    six.reraise(*result)
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Applications/anaconda/envs/my_pycalphad/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
RuntimeError: cannot release un-acquired lock```

**Comment by bocklund** [comment]
@olivia-higgins hasn't tested 1.16.3, but I am successfully using this on my machine with `dask 0.15.1`. 

I think that possibly something between 1.16.3 and 1.18.0 changed and our ImmediateClient might need to be less Immediate.

**Comment by bocklund** [comment]
Also cloudpickle is also reportedly seeing some issues also (https://github.com/dask/distributed/issues/1254).

I am running 0.2.2 on my machine and @olivia-higgins was running 0.3.1

**Comment by bocklund** [comment]
I have been able to reproduce this with a fresh install on Windows. A known workaround is to use ESPEI in MPI mode. For local machines, it is easiest to install MPI binaries. The suggested known working methods for installing MPI binaries are:

* Windows: Download and install a version from Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=47259 as suggested by the mpi4py package
* Mac: Install OpenMPI via Homebrew
* Linux: Install OpenMPI via the system package manager (tested working on Ubuntu 16.04)

**Comment by bocklund** [comment]
I matched the requirements on another machine to exactly mine that are known working using a `pip freeze` and installing from those. The issue still came up.

I'm thinking it must be something in the lazy ImmediateClient. If a less complicated solution is not apparent, then an alternative might be to allow locks to be serialized and pickled.

**Comment by bocklund** [comment]
I finally hit this issue on my Mac.

```python
Traceback (most recent call last):
  File "/Users/brandon/anaconda3/envs/espei/bin/espei", line 11, in <module>
    load_entry_point('espei', 'console_scripts', 'espei')()
  File "/Users/brandon/Projects/espei/espei/espei_script.py", line 237, in main
    run_espei(input_settings)
  File "/Users/brandon/Projects/espei/espei/espei_script.py", line 189, in run_espei
    deterministic=deterministic,
  File "/Users/brandon/Projects/espei/espei/mcmc.py", line 567, in mcmc_fit
    for i, result in enumerate(sampler.sample(walkers, iterations=mcmc_steps)):
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/emcee/ensemble.py", line 259, in sample
    lnprob[S0])
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/emcee/ensemble.py", line 332, in _propose_stretch
    newlnprob, blob = self._get_lnprob(q)
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
    results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
  File "/Users/brandon/Projects/espei/espei/utils.py", line 43, in map
    result = [x.result() for x in result]
  File "/Users/brandon/Projects/espei/espei/utils.py", line 43, in <listcomp>
    result = [x.result() for x in result]
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/client.py", line 158, in result
    six.reraise(*result)
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Users/brandon/anaconda3/envs/espei/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
RuntimeError: cannot release un-acquired lock
```

This is on ESPEI commit 5acb606 (on the single phase lnprob branch) running on 7 cores. I can try to merge #41 into that branch and see if I can reproduce the issue with the same settings.

**Comment by richardotis** [comment]
Can `ImmediateClient` be removed?

**Comment by richardotis** [comment]
Okay, so `emcee` needs a client which implements a `map` function. What if the implementation of `ImmediateClient` was changed to this:

```python
class ImmediateClient(Client):
    map = Client.gather
```

**Comment by bocklund** [comment]
`emcee` needs a`map` and expects that `map` to be blocking (i.e. returning values not futures).

`gather` collects the results from the async `map` and using that is essentially the change suggested by #41. I thought I was able to reproduce this error with #41 and that's why I didn't pursue it further, but I didn't keep a comment there to remind future me.

**Comment by bocklund** [comment]
Per https://github.com/dask/distributed/issues/780 this could also be an issue with logging module

**Comment by bocklund** [comment]
@richardotis suggested this is possibly contributed to by Locks in SymPy and that removing the fastcache package may be effective.
